services:
  - type: web
    name: mangafire-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      export PLAYWRIGHT_BROWSERS_PATH=./pw-browsers
      playwright install firefox
      playwright install-deps firefox
    startCommand: |
      export PLAYWRIGHT_BROWSERS_PATH=./pw-browsers
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
